fastlane_version "2.235.0"

default_platform :ios

platform :ios do
    desc "Runs all the tests"
    lane :test do
        scan(
            scheme: "Mocky_Tests_iOS",
            workspace: "./SwiftyMocky.xcworkspace",
            devices: ["iPhone 17"]
        )
    end

    desc "Runs all the tvOS tests"
    lane :test_tvos do
        scan(
            scheme: "Mocky_Tests_tvOS",
            workspace: "./SwiftyMocky.xcworkspace",
            devices: ["Apple TV"]
        )
    end
end

platform :mac do
    desc "Runs all the tests"
    lane :test do
        scan(scheme: "Mocky_Tests_macOS")
    end
end
