name: Build & Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  SwiftyMocky-Tests:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3'
      - name: Prepare for tests
        run: |
          rake pods
          rake update
          rake cli:assetize
          rake mock
      - name: Run tests iOS
        run: |
          fastlane ios test
      - name: Run tests tvOS
        run: |
          fastlane ios test_tvos
      - name: Run tests SwiftPM
        run: |
          swift test --enable-swift-testing
